package com.wod.entity;

public class Courses {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column courses.Course_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String courseName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.Course_id
     *
     * @return the value of courses.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.Course_id
     *
     * @param courseId the value for courses.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column courses.Course_name
     *
     * @return the value of courses.Course_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column courses.Course_name
     *
     * @param courseName the value for courses.Course_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName == null ? null : courseName.trim();
    }
}