package com.wod.entity;

public class Scores {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.Score_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private Integer scoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.Score
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.Student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String studentAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column scores.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String courseId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.Score_id
     *
     * @return the value of scores.Score_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public Integer getScoreId() {
        return scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.Score_id
     *
     * @param scoreId the value for scores.Score_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setScoreId(Integer scoreId) {
        this.scoreId = scoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.Score
     *
     * @return the value of scores.Score
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.Score
     *
     * @param score the value for scores.Score
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setScore(String score) {
        this.score = score == null ? null : score.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.Student_account
     *
     * @return the value of scores.Student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getStudentAccount() {
        return studentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.Student_account
     *
     * @param studentAccount the value for scores.Student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setStudentAccount(String studentAccount) {
        this.studentAccount = studentAccount == null ? null : studentAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column scores.Course_id
     *
     * @return the value of scores.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column scores.Course_id
     *
     * @param courseId the value for scores.Course_id
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    public Scores(String score, String studentAccount, String courseId) {
        this.score = score;
        this.studentAccount = studentAccount;
        this.courseId = courseId;
    }

    public Scores(){

    }
}