package com.wod.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String studentAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.student_password
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    private String studentPassword;

    public Student() {

    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_account
     *
     * @return the value of student.student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getStudentAccount() {
        return studentAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_account
     *
     * @param studentAccount the value for student.student_account
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setStudentAccount(String studentAccount) {
        this.studentAccount = studentAccount == null ? null : studentAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_name
     *
     * @return the value of student.student_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_name
     *
     * @param studentName the value for student.student_name
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.student_password
     *
     * @return the value of student.student_password
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public String getStudentPassword() {
        return studentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.student_password
     *
     * @param studentPassword the value for student.student_password
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    public void setStudentPassword(String studentPassword) {
        this.studentPassword = studentPassword == null ? null : studentPassword.trim();
    }

    public Student(String studentAccount, String studentName, String studentPassword) {
        this.studentAccount = studentAccount;
        this.studentName = studentName;
        this.studentPassword = studentPassword;
    }

    public Student(String studentAccount, String studentPassword) {
        this.studentAccount = studentAccount;
        this.studentPassword = studentPassword;
    }
}