package com.wod.dao;

import com.wod.entity.Courses;
import com.wod.entity.CoursesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoursesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    long countByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int deleteByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int deleteByPrimaryKey(String courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int insert(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int insertSelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    List<Courses> selectByExample(CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    Courses selectByPrimaryKey(String courseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByExample(@Param("record") Courses record, @Param("example") CoursesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByPrimaryKeySelective(Courses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table courses
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByPrimaryKey(Courses record);
}