package com.wod.dao;

import com.wod.entity.AvgScoresSubject;
import com.wod.entity.Scores;
import com.wod.entity.ScoresExample;
import java.util.List;

import com.wod.entity.StudentScores;
import org.apache.ibatis.annotations.Param;

public interface ScoresMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    long countByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int deleteByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int deleteByPrimaryKey(Integer scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int insert(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int insertSelective(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    List<Scores> selectByExample(ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    Scores selectByPrimaryKey(Integer scoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Scores record, @Param("example") ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByExample(@Param("record") Scores record, @Param("example") ScoresExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByPrimaryKeySelective(Scores record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table scores
     *
     * @mbg.generated Thu Jun 04 16:53:36 CST 2020
     */
    int updateByPrimaryKey(Scores record);

    /**
     * 查询所有学生成绩
     * @return 返回学生的学号、姓名、课程号、课程名、成绩，按课程分类
     */
    List<StudentScores> selectStudentScores();

    /**
     * 按科目分组查询平均成绩
     * @return 课程号，课程名、平均成绩（保留两位小数）
     */
    List<AvgScoresSubject> selectAvgScoresSubject();

    List<StudentScores> selectScoresPersonal(String studentAccount);
}